POST https://order-tracker-iot-26771.azurewebsites.net/api/OrderFn?code=SVC7d6FFU-akKbECnPtpayVPvYi_Jl40ara5505H9brmAzFuI1a_eA== HTTP/1.1
Content-Type: application/json

{
    "CustomerName": "Ania",
    "Price": 1500,
    "Status": "Dostarczone"
}

GET https://order-tracker-iot-26771.azurewebsites.net/api/OrderFn?code=SVC7d6FFU-akKbECnPtpayVPvYi_Jl40ara5505H9brmAzFuI1a_eA== HTTP/1.1
Content-Type: application/json

{}

DELETE https://order-tracker-iot-26771.azurewebsites.net/api/OrderFn?code=SVC7d6FFU-akKbECnPtpayVPvYi_Jl40ara5505H9brmAzFuI1a_eA== HTTP/1.1
Content-Type: application/json

{
    "Id": 10
}

PUT https://order-tracker-iot-26771.azurewebsites.net/api/OrderFn?code=SVC7d6FFU-akKbECnPtpayVPvYi_Jl40ara5505H9brmAzFuI1a_eA== HTTP/1.1
Content-Type: application/json

{
    "Id": 10,
    "Status": "Opłacone"
}

# FIND https://order-tracker-iot-26771.azurewebsites.net/api/OrderFn?code=SVC7d6FFU-akKbECnPtpayVPvYi_Jl40ara5505H9brmAzFuI1a_eA== HTTP/1.1
# Content-Type: application/json

# {
#     "Status": "Dostarczony"
# }